/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homeworkhttp;

public class App {


    public static void main(String[] args) throws Exception {
        HttpImageStatusCli cli = new HttpImageStatusCli();
        cli.askStatus();
    }
}
